about: NISER Software Development Group has been constituted to bring together people from various disciplines, who prefer a code-first approach to solving problems.

plugins:
    - jekyll-feed
    - jekyll-seo-tag
